### ISSUE TITLE
Phpunit lock version

### ISSUE THREAD

**Issue by pistej** [arron0/FormFactoryBuilder#5]
Since Phpunit version 6.0+  there is  Fatal error when running Unit tests

`PHP Fatal error:  Class 'PHPUnit_Framework_MockObject_Generator' not found in FormFactoryBuilder/vendor/arron/testit/TestIt/Tools/MockGenerator.php on line 26
`
Solution: fix phpunit version in composer.json to "phpunit/phpunit": "^5.7"

**Comment by arron0** [comment]
I restricted TestIt project to 3.* version which is compatible with phpunit <6 and with php5.6. phpunit 6 has some BCs (ex. namespaces) and is not compatible with php 5.6 so TestIt 4.* (which is supporting phpuni6) is has to have same BCs as well.
Sorry, it was my mistake :-)
